import { ModalData } from "./entrada_modal.provider";

export const ValoresEntrada: ModalData[] = [
  { description: 'Densidade sulfato de alumínio', value: '1300', measurement: 'kg/m³'  },
  { description: 'Densidade cloreto férrico', value: '1400', measurement: 'kg/m³'  },
  { description: 'Densidade policloreto de alumínio', value: '1250', measurement: 'kg/m³'  },
  { description: 'Viscosidade dinâmica da água', value: '1,029', measurement: 'x 10<sup>-4</sup>'  },
  { description: 'Peso específico da água', value: '1000', measurement: 'kg/m³'  },
  { description: 'Vazão para demanda industrial', value: '0', measurement: '' },
  { description: 'Velocidade da água no canal a jusante', value: '0,5', measurement: 'm/s' },
  { description: 'Distância do vertedor à comporta', value: '3', measurement: 'm' },
  { description: 'Tempo de detenção final da calha', value: '5', measurement: 's' },
  { description: 'Velocidade de escoamento 1', value: '0,18', measurement: 'm/s'  },
  { description: 'Velocidade de escoamento 2', value: '0,15', measurement: 'm/s'  },
  { description: 'Velocidade de escoamento 3', value: '0,10', measurement: 'm/s'  },
  { description: 'Concentração comercial policloreto de alumínio', value: '10,3', measurement: '%'  },
  { description: 'Concentração comercial sulfato de alumínio', value: '8,1', measurement: '%'  },
  { description: 'Concentração comercial cloreto férrico', value: '38', measurement: '%'  },
  { description: 'Concentração de sólidos na água clarificada', value: '2', measurement: '%'  },
  { description: 'Concentração de sólidos na água coagulada', value: '300', measurement: 'mg/L'  },
  { description: 'Concentração de sólidos no lodo', value: '30.000', measurement: 'mg/L'  },
  { description: 'Concentração comercial hidróxido de sódio', value: '12', measurement: '%'  },
  { description: 'Concentração comercial ácido fluossilícico', value: '20', measurement: '%'  },
  { description: 'Altura útil', value: '0,5', measurement: 'm' },
  { description: 'Tempo de contato decantador', value: '600', measurement: 's' },
  { description: 'Taxa de aplicação superficial', value: '35', measurement: 'm³/m².dia'  },
  { description: 'Velocidade crítica de sedimentação', value: '2,43', measurement: 'cm/min' },
  { description: 'Coeficiente de atrito', value: '0,003', measurement: '' },
  { description: 'Aceleração da gravidade', value: '9,81', measurement: 'm/s²'  },
  { description: 'Taxa de filtração', value: '240', measurement: 'm³/m².dia' },
];
